show transaction_isolation;

-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN;
UPDATE users SET age = 22 WHERE id = 1;
COMMIT;

BEGIN;
INSERT INTO users VALUES (5, 'Dima', 33);
COMMIT;

BEGIN;
INSERT INTO users(id, name, age) VALUES (7, 'John', 30);
COMMIT;

BEGIN;
SELECT * FROM users WHERE age > 17 FOR UPDATE;
UPDATE users SET age = age + 1;
COMMIT;

-- Phantom read
BEGIN;
INSERT INTO users VALUES (8, 'Kate', 23);
COMMIT;